plaidml/keras/backend_test.py, tile/codegen/codegen.proto, tile/targets/cpu/cpu.jsonnet
Also, added ability to measure from the backend tests.
Also removed the generation of CPU sencil for XSMM since it was causing a major perf problems. All the permutations are causing the stencil selection code to perform really poorly. Having handcoded set of values is much better here.
=> Add tests that demonstrate bad perf for the CPU jit

plaidml/keras/backend.py, plaidml/keras/backend_test.py, plaidml2/bridge/keras/__init__.py, plaidml2/bridge/keras/backend_test.py, plaidml2/op/__init__.py, plaidml2/op/lib/ops.cc, plaidml2/op/op.h, tile/lang/ast/ast.h, tile/lang/ast/gradient.cc
Adds (or in the case of var moves) operations to the shared EDSL op library. Currently adds abs, concatenate, expand_dims, squeeze, tile, transpose, and variance. Also adds or adjusts related Keras ops and the additional Keras backend ops softplus, softsign, stack, std, switch, and truncated_normal.
Note that concatenate is not working in most cases yet.
=> Add EDSL shared operations

plaidml/tile.py
Right now Keras unary ops (and other things using `plaidml.tile.unary_op`) can only handle tensor inputs, not float/int/numpy inputs. Use the same technique as binary_op to enable numeric inputs.
=> Enable shared unary ops to parse numerics

tile/cpu/main.cc, tile/platform/stripejit/program.cc, tile/pmlc/pmlc.cc, tile/targets/cpu/jit.cc, tile/targets/cpu/jit.h, tile/targets/cpu/test/jit.cc
Add configuration struct to stripejit API, containing the externals definition map. Add a flag controlling the generation of block-execution profiling code, so we don't have to clutter up the IR with all that overhead unless we need it.
=> stripejit configurability

plaidml/keras/backend_test.py
Enable sharding for backend_test. Note that this prevents forwarding command line arguments to `unittest` since it avoids `unittest.main`, so if those are needed fancier sharding code will be required. Run like `bazelisk run //plaidml/keras:backend_test -- --shard-count 10 --shard 3`.
=> Add sharding for backend_test

docs/troubleshooting.md, plaidml/keras/backend.py, plaidml/keras/backend_test.py, tile/lang/compose.cc
- Updated the plaidml backend code to check for the environment variable `PLAIDML_BATCHDOT_TF_BEHAVIOR` and switch between Theano (default) and TensorFlow-like behaviors.
- Updated the plaidml backend tests to set `skip_tensorflow` and `skip_theano` based on the environment variable from above
- Updated the troubleshooting docs to add instructions for using the environment variable `PLAIDML_BATCHDOT_TF_BEHAVIOR` and which runtime error it's typically associated with
- Updated the runtime message typically associated with `BatchDot` issues to direct users to the troubleshooting docs
=> Update BatchDot to switch between TensorFlow/Theano Behavior

tile/targets/cpu/jit.cc, tile/targets/cpu/jit.h
Enhancement of stripejit profiling feature: optionally record only the time spent in the body of each block's loop, excluding time spent on index increment & boundary testing overhead.
=> implement additional stripejit timer profiling for loop body segment

configure
For programmability's sake, I've added command-line arguments to the configure script for creating a conda environment and specifying a bazel cache URL.
```
usage: configure [-h] [--create_conda_env {y,n}] [--bazel_cache BAZEL_CACHE]
optional arguments:
-h, --help            show this help message and exit
--create_conda_env {y,n}
Create a conda environment for this repo, if one does
not already exist?
--bazel_cache BAZEL_CACHE
Enter a bazel cache server URL (omit argument to
disable)
```
=> Add command-line arguments to configure

plaidml2/bridge/keras/__init__.py, plaidml2/bridge/keras/backend_test.py, plaidml2/op/lib/ops.cc
The EDSL common softmax operation required a 2D input and made the second dim be the softmaxed axis. Allow arbitrary number of dimensions and choice of axis.
=> Extend EDSL common softmax to arbitrary axis

conda/unix.yml, conda/windows.yml
Trying to run plaidbench on common models causes issues on plaidml2 bridge (and possibly on plaidml)
=> Downgrade to keras 2.2.4

plaidml/keras/backend_test.py, tile/targets/cpu/compiler.cc, tile/targets/cpu/compiler.h, tile/targets/cpu/executable.cc
This changes adds the libxsmm_wimmdispatch calls when needed to support GEMM of (int8, uint8)--->int32.
It also has changes to the memory handling that result perf improvements.
With these changes the PlaidML GEMM for matrix 56, 56, 64 is now 12-13 x faster.
With fusing and no XSMM
===================
OK
Evaluating tf took: 0.02387213706970215 sec.
Evaluating tf took: 0.0019199848175048828 sec.
Evaluating tf took: 0.0031540393829345703 sec.
Evaluating tf took: 0.0017769336700439453 sec.
Evaluating tf took: 0.0019960403442382812 sec.
Evaluating tf took: 0.0017399787902832031 sec.
Evaluating tf took: 0.003194093704223633 sec.
Evaluating tf took: 0.0055942535400390625 sec.
Evaluating tf took: 0.0032258033752441406 sec.
Evaluating tf took: 0.004317045211791992 sec.
Evaluating pldml took: …
=> Implement calls to XSMM for all Stripe types. Perf improvements.

docs/integrating_into_ci.md
As requested by nGraph, I've created a piece of documentation that contains information that people integrating PlaidML into their own CI infrastructure might want to know. Let me know if you think anything else should be added.
=> Create external CI integration documentation

plaidml2/bridge/keras/__init__.py, tile/lang/ast/ast_ops.cc
This also extends the functionality of the EDSL Keras dropout op
=> Enable symbolic EDSL PRNG shape

tile/targets/cpu/llvm_cpu.jsonnet
This merges few blocks, resulting in better codegen.
=> Add more fusing passes to the llvm_cpu jit.

tile/targets/cpu/compiler.cc
There are cases where resnet50 (and keras) calls a conditional statement with first parameter not being boolean. Cast to satisfy the LLVM type system checks.
=> Fix a type error for conditional statement to make res50 training run.

plaidml2/bridge/keras/backend_test.py
This enables the use of input_shapes for the forward passes of backend_test (previously it had only affected the gradient portion of tests)
=> Enable symbolic shape forward pass testing

tile/targets/cpu/compiler.cc
For bad bit count of as_XXXXX functions add the number of bits that is incorrect to the error message.
=> Add the incorrect bit count to the error message.

plaidml2/bridge/keras/__init__.py
This is an implementation of the `is_placeholder()` for the keras backend of plaidml2. It doesn't include unit tests, because there weren't in the unit tests of plaidml. But let me know if they should be added.
=> Implement K.is_placeholder() in plaidml2 keras backend

tile/codegen/aggrinit.cc, tile/targets/cpu/llvm_cpu.jsonnet
Added also a prone_unused_refinement pass to remove unused efinments that might have been created during fusion, etc.
=> Use the outer named out refinement to initialize the inner aggr buffer

plaidml2/bridge/keras/backend_test.py
Title is self-explanatory. Some warnings do persist for some reason, couldn't find a way to remove them.
=> Remove numpy and tensorflow deprecation warnings in backend test of plaidml2

tile/targets/cpu/compiler.cc, tile/targets/cpu/compiler.h
After implementing scatter, gather, and agg_init, we had four different implementations of a ranged for loop. This change unifies loop generation code, for consistency & readability.
=> Refactor common loop generation code

plaidml/keras/backend.py, tile/lang/gen_stripe.cc
Fix type of contraction operations and assignments to be based on the inputs.
Changed the type of one_hot from BOOLEAN to FLOAT32 (after talking to Tim). The result of this operation is always used in float calculations and TF's type for the operation is float32 as well.
=> Fix type of contraction operations and assignments

pmlc/dialect/stripe/dialect.cc, pmlc/dialect/stripe/ops.cc, pmlc/dialect/stripe/ops.td
Currently awaiting changes to refs/allocs to clean those up, as well as Frank's shared util directory to add eltwise ops to he mix.  Blocks are more complex to fix, as are argument names, due to minor limitations in MLIR's parser.  TODO: consider make a PR against MLIR, how would we stage this?
=> Better printing

plaidml/keras/backend_test.py
The issue is that we use a float16 as an accumulator for the matrix elements. The sum grows to a point that adding more elements doesn't change the sum, because the number being added is less than the precision of the float16.
=> Disable the float16 test testRandomeNormalVariableMean

plaidml2/bridge/keras/__init__.py, plaidml2/bridge/keras/backend_test.py
Fix a crash when `None` is used for the `beta` or `gamma` parameter of batch normalization.
=> Fix batch normalization with None for beta/gamma

plaidml2/edsl/edsl_test.cc, plaidml2/edsl/edsl_test.py
Now that the padding pass is fixed, turn the tests we were skipping back on. Also add expected output in the python version (verified by hand).
=> Turn on fixed EDSL defract tests

tile/codegen/codegen.proto, tile/codegen/fuse.cc, tile/lang/gen_stripe.cc, tile/targets/gpu/amd.jsonnet, tile/targets/gpu/intel_gen9.jsonnet
1) Walkaround about the limit (31) of the kernel buffer arguments
2) Set the ZERO value as float type, consistent with the usual case
=> Fix the Metal compilation error on Catalina

plaidml2/op/op.h, plaidml2/op/op_test.cc
Eventually we want to connect the op lib to the C++ EDSL; for now, get sigmoid in there.
=> Connect sigmoid in op lib to C++ EDSL

pmlc/dialect/stripe/ops.td
New format looks like
```
stripe.aggregate "max" %O_1 %s_O : !fp32_4
```
=> Print MLIR aggregate with human-readable agg_op

plaidml2/edsl/edsl_test.cc, tile/base/platform.h, tile/base/platform_test.cc, tile/base/platform_test.h, tile/platform/local_machine/platform.cc, tile/platform/local_machine/platform.h, tile/platform/local_machine/program.cc, tile/platform/local_machine/program.h, tile/platform/local_machine/run_request.cc, tile/platform/local_machine/run_request.h, tile/platform/local_machine/shim.cc, tile/platform/local_machine/shim.h
The `Shim` was holding onto a `Program` that might have been freed. If the user decides not to wait on the `Program::Run` future (totally valid), then it's possible that the user might free the `Program` (indirectly) before the future has completed.
This ensures that the `Program` is pinned down by anything using it asynchronously.
=> Fix Program::Run race condition

plaidml2/op/op.h, plaidml2/op/op_test.cc
This PR includes op lib wrappers for:
* `hard_sigmoid`
* `max`
* `maximum`
* `min`
* `minimum`
I skipped over `image_resize` and `pool` for now because I want to build the fluid interface PoC first before thinking about ops that take in a high number of parameters.
=> More op lib wrappers

vendor/mlir/mlir.BUILD
Add the ability to build MLIR's `mlir-opt` through our build system (as `@mlir//:mlir-opt`).
=> Build mlir-opt

.bazelci/presubmit.yml
Let's see if this works.
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#macos-using-a-specific-version-of-xcode
=> pin xcode on bazelci hosted machines

pmlc/dialect/stripe/dialect.cc, pmlc/dialect/stripe/populate_tensor_ref_shape_analysis.cc, pmlc/dialect/stripe/populate_tensor_ref_shape_analysis.h
Analysis was not computed when retrieved using MLIR analysis manager.
=> [MLIR] Minor fixes to PopulateTensorRefShapeAnalysis

networks/oplib/BUILD, networks/oplib/resnet50.cc
This adds a ResNet50 implementation that does not use any framework, just the op library / EDSL. It is very minimal; it does not load weights or input data, and so can't be checked for correctness (especially dangerous considering the number of typos possible when writing networks without a framework). It is also currently built on the AST version of Stripe, not MLIR.
=> Add no-framework C++ EDSL resnet

pmlc/dialect/tile/contraction.cc, pmlc/dialect/tile/contraction.h, pmlc/dialect/tile/tests/legalize-to-stripe.mlir, tile/bilp/BUILD, tile/bilp/ilp_solver.cc, tile/bilp/ilp_solver.h, tile/bilp/test.cc, tile/lang/bound.cc, tile/lang/bound.h, tile/math/math_test.cc, tile/math/polynomial.cc, tile/math/polynomial.h
Allow the Tile dialect to store constraints as one-sided constraints by adding mechanisms to construct two-sided constraints from pairs of opposing parallel one-sided constraints.
=> Lower 1-sided constraints in Tile->Stripe

.bazelci/presubmit.yml
Apparently some of the latest deps for some of our tests require a newer glibc++
=> Use ubuntu 18.04 in bazel farm

plaidml2/edsl/edsl_test.cc, pmlc/dialect/stripe/from_mlir.cc
Before, the generated `CPUProgram`s using `as_*` ops would have statements like
```
int d3__s = 32;
float d3___X2 = as_uint(d3___X0, d3__s);
```
Now, they read
```
int d3__s = 32;
uint32 d3___X2 = as_uint(d3___X0, d3__s);
```
=> Added type to mlir cast

plaidml/plaidml_setup.py
The `plaidml-setup` message I added 2 days ago had an em dash (`—`) in it, which isn't available in ascii, which caused errors for our users when they tried to run `plaidml-setup`. I've replaced the em dash with a normal dash.
sorry 😢
=> fix setup message to conform to ascii

.pre-commit-config.yaml, environment-windows.yml, environment.yml
This will enable cleaner committing of python notebooks
=> Add nbstripout to precommit hooks

ci/plan.yml, plaidml/bridge/keras/__init__.py, plaidml/op/BUILD
This enables a subset of backend_test that is expected to currently pass in the standard CI for PRs.
=> Run a subset of backend_test in CI

plaidml/edsl/ffi.cc, pmlc/compiler/compiler.cc, pmlc/compiler/compiler.h, pmlc/dialect/tile/builder.cc
This is can be used to turn the textual representation of the tile dialect into a `Program`, which can then be used for running compiler passes.
Note: This doesn't yet populate the `arguments`, which is needed for execution. Let me know if you need that.
=> Add compiler API to convert tile source code into Program

pmlc/tools/pmlc-vulkan-runner/vulkan_runner_tests.cc
Replaced func to spv.func in vulkan runner to be compatible with updated MLIR
=> A vulkan runner patch

pmlc/dialect/pxa/analysis/BUILD, pmlc/dialect/pxa/analysis/strides.cc, pmlc/dialect/pxa/analysis/strides.h, pmlc/dialect/pxa/tests/strides.mlir, pmlc/dialect/pxa/transforms/registration.cc, pmlc/dialect/pxa/transforms/test_analysis.cc, pmlc/rt/xsmm.cc, pmlc/target/x86/tests/xsmm.mlir
- Improve naming of block arguments in `TestStrideInfoPass`, each argument is now given a unique name based on the inverse depth of the block in which the argument is induced.
- Add the ability to print `StrideInfo` for `AffineStoreOp` and `AffineReduceOp` in addition to `AffineLoadOp`.
- Add dot and convolution test cases to `strides.mlir`.
- Improve xsmm lowering test to include more complex input data patterns. Two are implemented, which are based on the formulas: `A[x, y] = x + y - 5` and `A[x, y] = x + y + i - 5` where `i = linear_offset(x, y)`. This is also extended to a 4D filling function to initialize convolution inputs.
=> Improve testing for xsmm op

networks/oplib/resnet50.mlir, plaidml/edsl/ffi.cc, plaidml/edsl/tests/edsl_test.cc, plaidml/edsl/tests/edsl_test.py, plaidml/op/op_test.cc, pmlc/conversion/tile_to_pxa/tests/dot.mlir, pmlc/conversion/tile_to_pxa/tests/double_dot.mlir, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc, pmlc/dialect/eltwise/ir/ops.td, pmlc/dialect/tile/builder.cc, pmlc/dialect/tile/builder.h, pmlc/dialect/tile/gradient.cc, pmlc/dialect/tile/ir/BUILD, pmlc/dialect/tile/ir/base.td, pmlc/dialect/tile/ir/builder.td, pmlc/dialect/tile/ir/dialect.cc, pmlc/dialect/tile/ir/ops.cc, pmlc/dialect/tile/ir/ops.td, pmlc/dialect/tile/tests/build-cion.mlir, pmlc/dialect/tile/tests/compute-bounds.mlir, pmlc/dialect/tile/tests/constant-fold.mlir, pmlc/dialect/tile/tests/padding.mlir, pmlc/util/interfaces.h, pmlc/util/interfaces.td
Rename and reorganize tile dialect ops so that they are less confusing. Split the dialect into two `.td` files so its clear which ops are used by the builder vs the rest of the system.
=> NFC: Tile dialect updates

WORKSPACE, pmlc/tools/pmlc-jit/BUILD, pmlc/tools/pmlc-vulkan-runner/BUILD, vendor/mlir/mlir.BUILD
This toolchain is useful for local development work on linux (mostly because ASAN is awesome).
This PR fixes the `llvm_toolchain` so that it continues to work on Windows (where it's just a NO-OP).
=> Fix support for clang toolchain on linux

bzl/plaidml.bzl, pmlc/compiler/BUILD, vendor/llvm/llvm.BUILD
There are many more upcoming changes I plan to make to allow downstream compilers to have more modular dependencies. At the moment, things like the GPU dialect have to be consumed downstream.
=> Fixes for downstream repos

plaidml/edsl/tests/edsl_test.cc, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
This fixes an issue with lowering tile to affine when I8 element types are used.
=> Cast scalar constants for affine.store

pmlc/dialect/tile/ir/ops.cc
Always set the AffineMap to empty one in case there are empty lower and upper bounds.
=> Fix an assertion that stop crashing tests

pmlc/dialect/tile/transforms/contraction.cc, pmlc/util/math/polynomial.cc, pmlc/util/math/polynomial.h
The same RangeConstraint can be expressed in two directions (e.g. `0 <= x < 5` is equivalent to `0 <= 4 - x < 5` -- recall that `x` is integral); this canonicalizes which direction is chosen.
=> Put RangeConstraints in canonical form

ci/plan.yml, plaidml/bridge/keras/backend_test.py, pmlc/dialect/tile/transforms/constant_types.cc, pmlc/dialect/tile/transforms/passes.td
Using of the GreedyPatternRewriteDriver is an overkill and exposed (at least on MacOS) an issue with not removing dependent operations when a triviallyDeadOperation is erased. This lead
s to inconsistent state in the workList for the pass that causes a destroyed operation to be processed.
=> Use a simple pattern match replacer for coinstant types rewrites

plaidml/bridge/keras/backend_test.py, pmlc/conversion/tile_to_pxa/tests/padding.mlir, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
Disable temporarily the do_grad option in the backend_tests, since it is not implemented yet.
Fix an issue with getting out of bounds in case of lowerBounds not 0 for ContractOp.
=> Fix all of the BoundCheck failing tests

plaidml/bridge/keras/__init__.py
Properly handle sending the pool mode (i.e. average or max) through the Keras backend to the FFI.
This partially fixes PlaidML-v1 PlaidBench Keras ResNet50 (a full fix will at a minimum also require https://github.com/plaidml/plaidml/pull/1044)
=> Fix Keras pooling

plaidml/bridge/keras/backend_test.py, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
Fixes the smallest positive vs most negative problem identified in https://github.com/plaidml/plaidml/pull/1063 by switching to +/-infinity for the initialization of min and max contractions respectively. Updates the test for max pool to find the previous error.
=> Fix max contractions of negatives

pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/conversion/pxa_to_affine/tests/contract.mlir
Fixes an ordering issue in PXA to Affine where reduce ops with no indexes were having their bodies moved to the end of their containing block. In particular, this meant that reductions initializing the output of a contraction to zero were being moved after reductions doing the core work of a contraction.
This fixes the bug where most backend tests using a contraction returned tensors of all 0s.
=> Fix contractions returning zeroes

pmlc/dialect/tile/ir/ops.cc, pmlc/dialect/tile/tests/build-cion.mlir
Adds canonicalization of SymbolicContractions with partially static shapes. I think it's forward progress, but this does not fully resolve this issues with PlaidBench ResNet50:
* At the end of compiling the network, PlaidBench crashes with unclear cause (not yet investigated).
* Network compilation performance is bad (like 5 minutes maybe on my Mac). I think (but haven't looked closely) that when computeShape is called it rebuilds & re-canonicalizes the entire network up to the selected op, and gets pretty bad when computeShape is called a bunch.
I'm uncertain whether the crash is related to this PR, or whether it has always existed and we're only now getting far enough to hit it. I'm therefore also uncertain whether to try to land this immediately or wait until investigating the crash.
=> Canonicalize with partially static shape

plaidml/edsl/tests/edsl_test.cc, pmlc/compiler/executable.cc, pmlc/testing/BUILD
The compiler adds an underscore, but on MacOS system symbols have no one. The Stripe code did similar thing.
Thanks Mars!
=> Fix system library lookup for MacOS

ci/plan.yml, pmlc/dialect/tile/builder.cc
Insert an elementwise copy when returning a value which is the result of a reshape, since the output needs to become a user-supplied buffer.
=> add workaround for return of reshape views; enable tests which now pass

ci/plan.yml
Compared the list of passing tests to the list in ci/plan.yml; this was the only one missing.
=> add testBatchNormAndUpdate to CI, since it passes OK

bzl/workspace.bzl, pmlc/dialect/pxa/analysis/strides.cc, pmlc/dialect/pxa/analysis/strides.h, pmlc/dialect/pxa/tests/autotile.mlir, pmlc/dialect/pxa/tests/fusion.mlir, pmlc/dialect/pxa/tests/stencil.mlir, pmlc/dialect/pxa/tests/strides.mlir, pmlc/dialect/pxa/transforms/fusion.cc, pmlc/dialect/pxa/transforms/passes.td, pmlc/target/x86/pipeline.cc
* Enforce stable order for fused IVs (to make tests deterministic)
* Prefix PXA transforms with `pxa-` for `pmlc-opt`
* Bump to latest plaidml/llvm-project
=> Add fusion tests

pmlc/dialect/pxa/ir/ops.td
Both affine.load and affine.store have setMemRef. We need setMemRef for affine.reduce for some passes, too.
=> Add setMemRef for affine.reduce

plaidml/edsl/tests/edsl_test.cc, plaidml/op/lib/ops.cc, plaidml/op/op.h, plaidml/op/op_test.cc, plaidml/testenv.h
I've been working with @tzerrell regarding some weirdness I've been seeing in my implementation of the `broadcast` op.
Essentially, I wrote a `broadcast` op, the tile code looks fine, but I run into the following errors when trying to test the code with `runProgram` or `checkProgram`.
```
error: 'func' op unsupported module-level operation
unknown file: Failure
C++ exception with description "could not convert to LLVM IR" thrown in the test body.
```
To try and debug, I created a test `CppEdsl.BroadcastNonOpLib` in `edsl_test.cc` that does a broadcast using _just_ EDSL code, and replicated the same code using the `broadcast` op in `op_test.cc`.
Program generated from EDSL code:
```
#map0 = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
#map1 = affine_map<(d0, d1, d2, d3) -> (d0, d2, …
```
=> Add broadcast to op lib

plaidml/bridge/openvino/src/plaidml_plugin/ops/unsqueeze.cpp, plaidml/bridge/openvino/src/plaidml_plugin/plaidml_util.cpp, plaidml/bridge/openvino/src/plaidml_plugin/plaidml_util.hpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/unsqueeze.cpp, vendor/openvino/workspace.bzl
Includes the axes-reading code previously in #1105.
This depends on the new unsqueeze test in https://github.com/plaidml/openvino/pull/4 and so is a draft until that lands.
=> Add Unsqueeze to OpenVINO plugin

plaidml/op/op_test.cc, pmlc/dialect/eltwise/ir/util.cc, pmlc/dialect/eltwise/ir/util.h, pmlc/dialect/tile/BUILD, pmlc/dialect/tile/builder.cc, pmlc/dialect/tile/ir/ops.cc, pmlc/dialect/tile/ir/ops.h, pmlc/dialect/tile/tests/build-cion.mlir, pmlc/dialect/tile/transforms/BUILD, pmlc/dialect/tile/transforms/make_program.cc, pmlc/dialect/tile/transforms/passes.h, pmlc/dialect/tile/transforms/passes.td
With the current implementation of floatx/intx, it's possible for the initial element type inference of a contraction to compute a higher-precision type. Later, once the constant types are materialized, we need to re-infer the element type as a symbolic contraction is being converted to a regular one.
=> Fix for #1122

networks/oplib/resnet50.cc, plaidml/bridge/openvino/src/plaidml_plugin/ops/convolution_backprop_data.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/convolution_backprop_data.cpp, plaidml/edsl/edsl.h, plaidml/op/__init__.py, plaidml/op/lib/ops.cc, plaidml/op/op.h
Adds the ConvolutionBackpropData op to the PlaidML OpenVINO plugin. Includes several parts:
1. Actually adding the op
2. Reformatting the tests to make the linter happy
3. Extending the oplib convolution to allow it to infer the result size for ConvDerivMode::DATA. Add a new parameter to the oplib conv to enable this (IMO we don't want it on by default; it's forced to make assumptions about the possible size as multiple input data sizes correspond to the same output size and I don't think we should make such assumptions without an explicit request)
4. Add some fancy template metaprogramming code to the Convolution Fluent API to allow multiple integer vector types to be used as inputs.
5. Advances the OpenVINO reference
Sorry that these are bundled in one PR, ~but no part of this is tested …
=> Add OpenVINO plugin ConvolutionBackpropData op

plaidml/bridge/openvino/src/plaidml_plugin/ops/avg_pool.cpp, plaidml/bridge/openvino/src/plaidml_plugin/ops/max_pool.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/pooling.cpp
A collaboration with @cnamrata15 to fix pooling test failures. There are still 28 failing pooling tests, but they are all failing on the nGraph interpreter reference implementation side due to known errors (commented on in the OV code we got these test cases from).
=> Fix OpenVINO plugin pool failures

plaidml/bridge/openvino/src/plaidml_plugin/ops/logical_not.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/logical_not.cpp
Tests fail due to issues with specifying boolean input/output in the test.
=> Added logical not op

plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/convolution_smoke.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/eltwise.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/pooling_smoke.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/reshape.cpp
Adds smoke tests covering all OpenVINO plugin ops without known errors in the op and/or its tests. These tests should be suitable for CI -- they ran in 10 seconds on my linux setup -- but I'm adding Matt as a reviewer so he can complain if I'm wrong about that.
~Also fix the bug that inspired these tests: MatMul had gotten out of sync with our OpenVINO fork, and we had untested and unnoticed compilation errors. CI should now yell at us if we overlook that again. This is in a separate commit for ease of review.~ This is instead addressed in https://github.com/plaidml/plaidml/pull/1191
=> Create OpenVINO plugin smoke tests

plaidml/bridge/openvino/src/plaidml_plugin/ops/floor_mod.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/fake_quantize.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/floor_mod.cpp
Includes minor fixes discovered on enabling the tests.
Note that FloorMod isn't re-enabled due to a reference implementation error. But, as best as I can tell without a reference implementation, FloorMod is working.
=> Enable OpenVINO test for newly legalizable ops

plaidml/exec/exec.h
Fix a potential lifetime issue when a `Binder` is destroyed before an `Executable`.
=> Fix binder lifetime bug

plaidml/op/op_test.cc, pmlc/target/x86/xsmm_stencil.cc
Note: These convolutions should have a valid XSSM lowering, but currently there is a bug in lowering, so we simply skip optimizations for this case.
=> Fix for strided convolutions in XSMM.  

pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/dialect/pxa/ir/ops.cc, pmlc/dialect/pxa/ir/ops.td, pmlc/dialect/pxa/tests/ops.mlir
This is needed to allow us to use the data flow analysis mechanisms that the AffineReduceOp exposes/utilizes, so Fusion and other passes can operate on the AffineVectorReduceOp.
=> Add AffineVectoreReduce instruction to the pxa layer.

pmlc/dialect/pxa/ir/ops.td, pmlc/dialect/pxa/transforms/BUILD, pmlc/dialect/pxa/transforms/passes.h, pmlc/dialect/pxa/transforms/stencil_gemm.cc, pmlc/target/x86/BUILD, pmlc/target/x86/heatmap.h, pmlc/target/x86/heatmap_impl.cc, pmlc/target/x86/pipeline.cc, pmlc/target/x86/xsmm_lowering.cc
Generalize the stencil pass so that it is specific to GEMMs rather than XSMM.
=> XSMM & Stencil cleanups

pmlc/dialect/pxa/analysis/BUILD, pmlc/dialect/pxa/analysis/affine_expr.cc, pmlc/dialect/pxa/analysis/affine_expr.h, pmlc/dialect/pxa/analysis/strides.cc, pmlc/dialect/pxa/analysis/strides.h, pmlc/dialect/pxa/tests/autotile.mlir, pmlc/dialect/pxa/tests/grn.mlir, pmlc/dialect/pxa/transforms/resize_tmps.cc, pmlc/dialect/pxa/transforms/tile.cc
Updates to StrideInfo, Tiling and ResizeTmps so that they work on non-canonical affine loops.
=> Changes to StrideInfo and some fixes to tiling and resize

plaidml/bridge/keras/backend_test.py, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
This was the issue blocking the sparse categorical crossentropy backend tests. Related to #1249.
=> Pick float vs int comparison for contractions based on type of comparands, not result

bzl/bazel.rc, bzl/plaidml.bzl, plaidml/BUILD, plaidml/edsl/tests/edsl_test.cc, plaidml/testenv.cc, pmlc/lit.bzl, pmlc/lit.cfg.py
This commit adds two Bazel command line flags:
--//plaidml:device=&lt;device&gt; -- sets the test execution device
--//plaidml:target=&lt;target&gt; -- sets the test compilation target
For now, the device defaults to 'llvm_cpu.0', and the target must be
'llvm_cpu'.
=> Define --//plaidml:device and --//plaidml:target

pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc, pmlc/conversion/tile_to_pxa/tests/cast.mlir, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc, pmlc/dialect/stdx/ir/ops.cc, pmlc/dialect/stdx/ir/ops.td
Tile to PXA lowering has been converting all ints to float using sitofp, since MLIR std dialect does not include uitofp. Add a stdx.uitofp which lowers to llvm.uitofp so createCastOp can generate appropriately signed conversions.
Fixes #1256
=> add stdx.uitofp operation with lowering to llvm and use for casting

plaidml/edsl/ffi.cc, pmlc/compiler/program.cc, pmlc/compiler/program.h
Passes can be dumped to a directory by using the `PLAIDML_DUMP` env var. The directory specified will be created if it does not yet exist. It does not clear the directory, so care must be taken to clear it before each run.
=> Add support for dumping passses to a directory

pmlc/dialect/pxa/transforms/autotile.h
With the knowledge of the previous best cost in autotiling pass, we could skip heavy tests in the cost model if the cost of the current plan is already not the best.
=> Add best cost in autotile cost model

plaidml/BUILD, plaidml/bridge/openvino/BUILD, plaidml/bridge/openvino/src/plaidml_plugin/plaidml_executable_network.cpp, plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD, plaidml/bridge/pytorch/BUILD, plaidml/core/BUILD, plaidml/edsl/BUILD, plaidml/edsl/ffi.cc, plaidml/edsl/tests/BUILD, plaidml/exec/BUILD, plaidml/op/BUILD, pmlc/BUILD, pmlc/all_dialects.cc, pmlc/all_passes.h, pmlc/rt/vulkan/tests/BUILD, pmlc/target/demo/BUILD, pmlc/target/intel_gen/passes.h, pmlc/target/intel_gen/pipeline.cc, pmlc/target/x86/BUILD, pmlc/target/x86/passes.h, pmlc/target/x86/pipeline.cc, pmlc/target/x86/register.cc, pmlc/tools/pmlc-jit/BUILD, pmlc/tools/pmlc-jit/pmlc-jit.cc, pmlc/tools/pmlc-opt/BUILD, pmlc/tools/pmlc-opt/pmlc-opt.cc, pmlc/tools/pmlc-vulkan-runner/BUILD, pmlc/tools/pmlc-vulkan-runner/pmlc-vulkan-runner.cc
* Provide support for allowing external compilers to decide which targets to include.
* Decouple lib and test in openvino bridge.
* All dialects must be registered, until this lands: https://reviews.llvm.org/D85622
* A target is registered via a static initializer.
* OpenVINO tests no longer hard-code the target, instead use the PLAIDML_TARGET env var.
=> Support for 3rd party compilers

bzl/workspace.bzl, pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/conversion/pxa_to_affine/tests/vector.mlir
This relies on: https://github.com/plaidml/llvm-project/pull/24
Without the custom builder, `affine.vector_load` op verification was failing. It's unclear how to fix this without having a custom builder.
=> Use AffineVectorLoadOp/AffineVectorStoreOp builders

bzl/bazel.rc
Currently the OpenVINO tests use `plaidml::Settings` to determine which device/target to run on. Therefore, we need to have these env vars included so that CI will work. A PR that will use command line args instead to make things more hermetic is very welcome!
@tzerrell Is it possible to use `//plaidml:device` and `//plaidml:target` command line arguments?
=> Fix bazel buildkite farm

pmlc/testing/gtest_main.cc
Signed-off-by: xin1.wang <xin1.wang@intel.com>
=> Fix gtest_filter with skip_test_file on intel_gen target.

pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/dialect/pxa/analysis/strides.cc, pmlc/dialect/pxa/analysis/strides.h, pmlc/dialect/pxa/analysis/uses.cc, pmlc/dialect/pxa/ir/ops.cc, pmlc/dialect/pxa/ir/ops.td, pmlc/dialect/pxa/tests/dataflow_opt.mlir, pmlc/dialect/pxa/tests/fusion.mlir, pmlc/dialect/pxa/tests/resize_tmps.mlir, pmlc/dialect/pxa/transforms/cache.cc, pmlc/dialect/pxa/transforms/cache.h, pmlc/dialect/pxa/transforms/stencil.cc, pmlc/dialect/pxa/transforms/stencil.h, pmlc/dialect/pxa/transforms/tile_accumulate.cc, pmlc/dialect/pxa/transforms/vectorize.cc, pmlc/target/x86/xsmm_lowering.cc
* Move StrideInfo and related utilities into pxa namespace.
* Rename mem argument to memref in PXA ops for consistency.
* Mark PxaLoadOp as NoSideEffect (there are presently issues with attempting the same with PxaReduceOp).
* Fix existing PXA tests to return results, as required by the PXA dialect.
* Add flatOuter() and flatInner() to RelativeAccessPattern, which provides the 1-dimensional linearized strides on a per IV basis.
* Allow pxa::getOriginalDef() to return nullptr if the value is defined by a BlockArgument.
* Cache transformations now return a CacheInfo.
=> Improvements to utilities

pmlc/target/intel_gen/pass_detail.h, pmlc/target/intel_gen/passes.h, pmlc/target/intel_gen/passes.td, pmlc/target/intel_gen/pipeline.cc
As of this commit, many of the remaining EDSL tests that fail are caused by not having lowerings for our various stdx ops in https://github.com/plaidml/plaidml/blob/plaidml-v1/pmlc/conversion/gpu_to_spirv/gpu_to_spirv.cc.  At this point it should be a straightforward (if tedious) process to add such lowerings, and in many cases, the needed additions to the SPIRV dialect.
=> Get SinH etc to lower to GPU dialect.

pmlc/dialect/pxa/transforms/vectorize.cc
Apparently we were just getting lucky that the free didn't corrupt anything on linux.
=> Move increment to the correct place

plaidbench/plaidbench/core.py
Sets stopwatch time as duration_per_example in the absence of more accurate kernel timings.  For ResNet:
```
resnet50             1576.95 ms                1576.95 ms / 0.63 fps
Correctness: PASS, max_error: 7.918380106275436e-06, max_abs_error: 1.4603137969970703e-06, fail_ratio: 0.0
{'backend': 'plaid',
'batch_size': 1,
'compile_duration': 14.441735982894897,
'correct': True,
'duration_per_example': 1.5769538879394531,
'examples': 1,
'fail_ratio': 0.0,
'max_abs_error': 1.4603137969970703e-06,
'max_error': 7.918380106275436e-06,
'model': 'resnet50',
'tile_duration_per_example': 1.5769538879394531}
```
=> use stopwatch for v1 kernel timing

pmlc/rt/vulkan/vulkan_invocation.cc, pmlc/rt/vulkan/vulkan_invocation.h
Command:
```
PLAIDML_TARGET=intel_gen PLAIDML_DEVICE=vulkan.0 PLAIDML_VERBOSE=1 bazelisk run //plaidml/bridge/keras:backend_test -- TestBackendOps.resnetLayer1
```
Prints:
```
2020-09-11 15:07:57,987 VERBOSE-1 [default] Instantiating Vulkan device: Intel(R) Iris(R) Plus Graphics 650 (Kaby Lake GT3e) (KBL GT3)
2020-09-11 15:07:58,008 VERBOSE-1 [default] Overall Vulkan time: 7.27317ms
2020-09-11 15:07:58,008 VERBOSE-1 [default]   Vulkan kernel exec time: 0.47525ms
2020-09-11 15:07:58,009 VERBOSE-1 [default]   Vulkan kernel exec time: 6.35542ms
2020-09-11 15:07:58,009 VERBOSE-1 [default] Total Vulkan kernels: 2
2020-09-11 15:07:58,009 VERBOSE-1 [default] Total Vulkan kernel exec time: 6.83067ms
2020-09-11 15:07:58,009 VERBOSE-1 [default] Percentage Vulkan kernel exec time: 93.916%
2020-09-11 …
```
=> add Vulkan kernel timing

plaidbench/plaidbench/frontend_keras.py, plaidml/edsl/__init__.py
Make comparison to v0 apples to apples, improves kernel times to 43ms, see my email for details.
=> 'Fix' batch norm folding support in plaidbench

plaidml/bridge/tensorflow/tests/i3d_test_gen.py
#1367 was experiencing some errors due to stale TF models being left over from previous builds.
Upon further examination, I noticed that `hub.KerasLayer` was caching models outside of the temporary directory created within the test.
I've modified the `TFHUB_CACHE_DIR` environment variable to specify that the cache should be created in the temporary directory.
=> Fix caching issue in TF tests

pmlc/conversion/gpu/gpu_to_vulkan.cc, pmlc/conversion/gpu/kernel_outlining.cc, pmlc/dialect/pxa/transforms/subgroups.cc, pmlc/rt/vulkan/vulkan_device.cc, pmlc/rt/vulkan/vulkan_device.h, pmlc/rt/vulkan/vulkan_invocation.cc, pmlc/rt/vulkan/vulkan_invocation.h, pmlc/rt/vulkan/wrappers.cc, pmlc/target/intel_gen/affine_index_pack.cc, pmlc/target/intel_gen/subgroup_broadcast.cc
Use block.x as subgroup size of all kernels.  TODO: We should probably add support for subgroup size control to the upstream GPU dialect.
=> Plumb subgroup size control down to vulkan

pmlc/target/intel_gen_ocl_spirv/pass_detail.h, pmlc/target/intel_gen_ocl_spirv/passes.h, pmlc/target/intel_gen_ocl_spirv/passes.td, pmlc/target/intel_gen_ocl_spirv/pipeline.cc, pmlc/target/intel_gen_ocl_spirv/spirv_target.cc, pmlc/target/intel_gen_ocl_spirv/sub_group_size.cc, pmlc/target/intel_gen_ocl_spirv/tests/subgroup_size.mlir
This change adds lowering for sub-group size based on first block
dimension, same as it is done for Vulkan.
=> [OpenCL] Add temporary sub-group size lowering

pmlc/dialect/pxa/tests/fusion-match.mlir, pmlc/dialect/pxa/tests/fusion.mlir, pmlc/dialect/pxa/transforms/fusion.cc, pmlc/dialect/pxa/transforms/passes.h, pmlc/dialect/pxa/transforms/passes.td
If exactly-match is true, fuse the loops with only exactly matched indices. The default value is false.
In GRN case, apply one fusion pass with exactly-match==true and another pass with exactly-match==false. It would fuse GRN as a single big loop.
=> Add exactly-match option for fusion pass

pmlc/dialect/comp/tests/minimize_allocations.mlir, pmlc/dialect/comp/transforms/BUILD, pmlc/dialect/comp/transforms/minimize_allocations.cc, pmlc/dialect/comp/transforms/passes.h, pmlc/dialect/comp/transforms/passes.td, pmlc/target/intel_gen_ocl_spirv/pipeline.cc
This is very rough and naive first attempt at solving this problem.
In ResNet-50 this reduces number of `comp.alloc` ops from 716 down to 72.
=> [comp] Add pass to reduce number of device allocations

pmlc/target/intel_gen/BUILD, pmlc/target/intel_gen/pipeline.cc
The loop unrolling gives the following benefits (specific run numbers below):
resnetLayer1: 2.7 %
resnetLayer2: 3.4 %
Whole resnet50: 3.3 %
Layer1:
======
W/t LoopUnroll
2020-10-07 23:47:40,207 VERBOSE-1 [default] JITing for device: vulkan.0
2020-10-07 23:47:40,243 VERBOSE-1 [default] Overall Vulkan time: 6.01925ms
2020-10-07 23:47:40,243 VERBOSE-1 [default] Total Vulkan kernels: 6
2020-10-07 23:47:40,243 VERBOSE-1 [default] Total Vulkan kernel exec time: 4.7215ms
2020-10-07 23:47:40,243 VERBOSE-1 [default] Percentage Vulkan kernel exec time: 78.44%
2020-10-07 23:47:40,243 VERBOSE-1 [default] Total Vulkan memory transfers: 5
2020-10-07 23:47:40,243 VERBOSE-1 [default] Total (esimtated) Vulkan memory transfer time: 1.29775ms
2020-10-07 23:47:40,243 VERBOSE-1 [default] Percentage …
=> Add and integrate UnrollLoop pass in the intel_gen pipeline.

pmlc/target/x86/pipeline.cc
The result is 12% perf improvement on a single core. The best results were achieved with unroll  factor  of 32.
Overall, the perf of PlaidML v1 now is 33.31% better on single core (Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz) CPU, compared to Stripe (v0) of PlaidML.
Data:
PLAIDML-STRIPE-V0
Command: PLAIDML_USE_STRIPE=1 taskset -c 10  bazelisk run //plaidbench:bin -- -n 1000  resnet50
-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS
-----------------------------------------------------------------------------------------
resnet50             160.32 ms                 158.90 ms / 6.29 fps
Correctness: PASS, max_error: 8.240351235144772e-06, max_abs_error: 1.1920928955078125e-06, fail_ratio: …
=> Add loop unrolling to the x86 pipeline.

pmlc/conversion/gpu_to_spirv/gpu_to_spirv.cc, pmlc/conversion/gpu_to_spirv/passes.h
ResNet-50 running in full with conformance - checked with `plaidbench keras`.
=> [OpenCL] Add lowering for std.exp to spv.OCL.exp

plaidml/core/ffi.cc, plaidml/core/internal.h, plaidml/edsl/__init__.py, plaidml/edsl/edsl.h, plaidml/edsl/ffi.cc, plaidml/edsl/tests/edsl_test.cc, plaidml/edsl/tests/edsl_test.py, plaidml/ffi.py, plaidml/op/__init__.py, plaidml/op/ffi.cc, plaidml/op/ffi.h, plaidml/op/lib/ops.cc, plaidml/op/op.h, plaidml/op/op_test.cc, plaidml/plaidml_link.jsonnet, pmlc/ast/ast.cc, pmlc/ast/ast.h, pmlc/ast/builder.cc, pmlc/ast/eval.cc, pmlc/ast/eval.h, pmlc/compiler/program.cc, pmlc/compiler/program.h
Adding the concept of a `TensorLens`. A lens is used to provide a translation map between some `source` logical layout into some `target` logical layout. Op authors can use a lens so that they can focus on writing the op in some canonical logical layout.
Note that these logical layouts have no relation to the physical layout that a tensor will have in memory. This should be specified by users for inputs/outputs/constants and decided on by the compiler for intermediates.
See the `reorg_yolo` op for an example of its usage.
=> [edsl] Add support for layout-agnostic ops

pmlc/dialect/pxa/transforms/dataflow_opt.cc, pmlc/dialect/pxa/transforms/passes.h, pmlc/dialect/pxa/transforms/passes.td, pmlc/dialect/pxa/transforms/resize_tmps.cc, pmlc/target/intel_gen/pipeline.cc, pmlc/target/intel_gen_ocl_spirv/pipeline.cc
Added vector ops support.
Added option to apply only to allocOp in nested ops (right now resizing global mem causes output verification fails)
=> resizeTmpPass improvements

pmlc/target/x86/pipeline.cc
When it is unknown manufacturer the physical cores could be reported as 0. Handle this case in the pipeline setup.
=> Handle case of 0 physical cores reported

plaidml/op/lib/ops.cc
Accept `TensorDim`s for the `repeats` parameter of the oplib function `repeat`. This is intended to help us avoid `compute_shape` in the OV Bucketize code in https://github.com/plaidml/openvino/pull/90
=> Allow TensorDims to be used in Repeat

plaidml/op/op.h, plaidml/op/op_test.cc
Upgrade the API for repeat to enable the use of the new TensorDim repeats parameter, which I overlooked in #1518.
=> Update Repeat to Fluent API

pmlc/conversion/gpu_to_spirv/BUILD, pmlc/conversion/gpu_to_spirv/gpu_to_spirv.cc, pmlc/dialect/pxa/analysis/affine_constraints.cc, pmlc/dialect/pxa/tests/vectorize-mem_ops.mlir, pmlc/dialect/pxa/transforms/BUILD, pmlc/dialect/pxa/transforms/passes.h, pmlc/dialect/pxa/transforms/passes.td, pmlc/dialect/pxa/transforms/vectorize_mem.cc, pmlc/dialect/stdx/ir/ops.td, pmlc/target/intel_gen/pipeline.cc, pmlc/target/intel_gen/subgroup_broadcast.cc, pmlc/target/intel_gen/tests/subgroup_block_ops.mlir, pmlc/target/intel_gen_ocl_spirv/pipeline.cc, pmlc/target/intel_gen_ocl_spirv/spirv_target.cc
Things that are missing in llvm upstream, before we can have pull this in:
- New SPIRV Op OpVectorExtractDynamic and lowering of vector.extract_element to SPIRV (https://reviews.llvm.org/D90679)
- Updates to Vector size verification (https://reviews.llvm.org/D90683)
Currently only vector_load supported, WIP support for vector write as well
=> Vectorize memory ops

pmlc/dialect/tile/ir/eltwise.cc
Sometimes we want the result of a Tensor multiple 0 to be still a Tensor such as in [a workaround for embedding bag offsets sum ](https://github.com/Flex-plaidml-team/openvino/pull/5/files#diff-4e93753e3ae0a26abb5bfdebfd81e3ccbddf047c1d89c6cefac41c840b1a5f8eR76).
The following test currently does not get compiled. 
I removed the corresponding MulOp fold pattern in this patch so we do not need the workaround in the example above. Please advice if there is a better way to fix this.
TEST_F(CppEdsl, MulZero) {
auto I = Placeholder(DType::FLOAT32, {3, 3});
auto O = I * 0;
auto program = makeProgram("mul_zero", {I}, {O});
}
=> Disable tile.MulOp fold pattern with 0 when result() and rhs() have different datatypes

pmlc/conversion/comp_to_llvm/comp_to_ocl.cc, pmlc/conversion/comp_to_llvm/tests/comp_to_ocl.mlir, pmlc/conversion/gpu_to_comp/gpu_to_comp.cc, pmlc/conversion/gpu_to_comp/tests/gpu_to_comp.mlir, pmlc/dialect/comp/analysis/mem_sync_tracker.cc, pmlc/dialect/comp/ir/dialect.cc, pmlc/dialect/comp/ir/ops.td, pmlc/dialect/comp/ir/types.cc, pmlc/dialect/comp/ir/types.h, pmlc/dialect/comp/tests/invalid.mlir, pmlc/dialect/comp/tests/minimize_allocations.mlir, pmlc/dialect/comp/tests/remove_redundant_rw.mlir, pmlc/dialect/comp/transforms/minimize_allocations.cc, pmlc/rt/opencl/opencl_invocation.cc, pmlc/rt/opencl/opencl_invocation.h, pmlc/rt/opencl/opencl_wrappers.cc
Combining the copy and the alloc prevents us from hoisting the alloc, and doesn't get us a synchronization event for the data copy.  If this optimization turns out to be important, I think it'd be better handled as part of the lowering to LLVM.
=> Remove src memref from comp.alloc

plaidml/bridge/openvino/CMakeLists.txt, plaidml/bridge/openvino/benchmark_app/CMakeLists.txt
This avoids the need for special LD_LIBRARY_PATH settings. It also deposits the binary in the usual `bin/intel64/Release` directory.
=> Add support for building benchmark_app

pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc, pmlc/conversion/stdx_to_llvm/tests/pack.mlir, pmlc/dialect/stdx/ir/ops.cc, pmlc/dialect/stdx/ir/ops.h, pmlc/dialect/stdx/ir/ops.td
Pack + unpack support in preparation for init/fini goo.  Note: pack mallocs, unpack doesn't free, the assumption here is that returned allocations will have their lifetime managed by outer API.
=> Adding tuple pack/unpack ops + lowerings

ci/conda/tensorflow.yml, conda/unix.yml, conda/windows.yml, plaidbench/setup.py
It appears the h5py v3.0.0+ has made some incompatible changes:
https://github.com/tensorflow/tensorflow/issues/44467
=> Fix for broken h5py dependency

pmlc/dialect/layer/ir/ops.td
Original definition of layer dialect BoxOp was erroneously marked [NoSideEffect], but this is not a reasonable guarantee.
=> layer.box op may contain side effects; do not tag NoSideEffect

pmlc/target/intel_gen_ocl_spirv/CMakeLists.txt, pmlc/target/intel_gen_ocl_spirv/access_qualifiers.cc, pmlc/target/intel_gen_ocl_spirv/passes.h, pmlc/target/intel_gen_ocl_spirv/passes.td, pmlc/target/intel_gen_ocl_spirv/pipeline.cc, pmlc/target/intel_gen_ocl_spirv/tests/access_qualifiers.mlir
Added this pass on spirv level so we would not need to propagate the read only attribute all the way down. Also we need to set it per kernel as some kernel use same buffers for read, others for write.
I tried to add the NoWrite enum to spirv dialect instead of adding magic number, but seems like it is kind of pandora's box when I tried to add Function Parameter Attribute Adds to SPIRVBase.td using provided mlir scripts. There are tons of new Extensions to be added (which seems need to be done manually), not sure if it is related directly with this change or lack of new updates lately. I also got problems with lack of definitions for the NVidia's extensions, so decided to abandon this and fix for magic number for now.
=> Access qualifier for read only buffers pass

pmlc/target/intel_gen_ocl_spirv/BUILD, pmlc/target/intel_gen_ocl_spirv/CMakeLists.txt, pmlc/target/intel_gen_ocl_spirv/pipeline.cc, pmlc/transforms/BUILD, pmlc/transforms/CMakeLists.txt, pmlc/transforms/hoisting.cc
Excluded constant ops from hoisting, due to constant folding problems in the lower dialect canonicalizations.
Changed ‘maybeCrossFunc’ to ‘inInit’ per proposition from Jeremy.
=> Hoisting added to gpu ocl pipeline

pmlc/dialect/pxa/transforms/reorder_layouts.cc, pmlc/dialect/pxa/transforms/reorder_layouts.h, pmlc/target/intel_gen_ocl_spirv/reorder_layouts.cc
In this checkin I assume that when stdx.unpack op is present then init/main/fini functions are valid and contain single pack\unpack op.
I am going to add some lit tests later.
=> Weights reorders moved to init function

plaidml/edsl/tests/edsl_test.cc, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
As discussed in #1612, a unified API for `scatter` with an initialization tensor for all cases is preferred.
=> add initialization tensor to scatter summing case

plaidml/bridge/openvino/ops/activations.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/activation.cpp, plaidml/op/lib/ops.cc
Fixes a problem with ReLU variants where parameters of a different type than the input could cause type mismatches in `select`. Restores tests for these ops.
=> Fix ReLUs and re-enable tests

pmlc/dialect/pxa/transforms/reorder_layouts.cc, pmlc/dialect/pxa/transforms/reorder_layouts.h, pmlc/dialect/pxa/transforms/vectorize_mem.cc, pmlc/target/intel_gen_ocl_spirv/reorder_layouts.cc
1. Reorder_layouts: Move cleaning up outdated unpackops after the optimizations are done, due to sporadic crashes on windows
2. Vectorize_mem: include values from unpackop as a global memory, which unblocks this optimization after init-fini changes
=> Unpack fixes

conda/unix.yml, environment-windows.yml
Pinned pyyaml to 5.3.1 as pypi was updated to 5.4 today (01-19-2021) and plaidml-v1 build fails.
=> Pin pyyaml to 5.3.1

plaidml/bridge/openvino/ops/round.cpp
Using `floor` instead of `cast` to get the integer part.
=> Fix openvino RoundHalfToEven

plaidml/bridge/openvino/ops/mat_mul.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/mat_mul.cpp
Fix the problem memtioned by Tim at https://github.com/plaidml/plaidml/pull/1679#discussion_r563909981.
I simply use `op::repeat` to fix the problem because when we need broadcast semantics over the leading "batch" dimensions, they are always equal to 1. I think in this case `op::repeat` and `op::broadcast` perfom the same functionality and `op::repeat` is less complex. What do you think @tzerrell ?
=> fix matmul and add new test cases

plaidml/bridge/openvino/ops/prior_box.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/prior_box.cpp
Ngraph's implementation of number_of_priors use a weird way to process density (https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/prior_box.cpp#L116), this is different from the reference it provided (https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/reference/include/ngraph/runtime/reference/prior_box.hpp#L159) . This conflict makes the node output shape is different from the real output so it only work well when the fixed_ratio size is one.  Change the test case of PriorBox to follow this implicit rule and wait for their fix now.
Signed-off-by: xin1.wang <xin1.wang@intel.com>
=> PrioBox only supports fixed_ratio with one element now.

plaidml/bridge/openvino/ops/reshape.cpp, plaidml/op/lib/ops.cc
Reshape with an autofill dim was disabled when coming from OpenVINO (as we were using a non-negative type and replacing the -1 autofill token with 0). Moreover, it had bugs when it _was_ used from getting a reference to an element of a vector and then resize that vector. This PR addresses both of those.
=> Re-enable & fix reshape with autofill

plaidml/bridge/openvino/ops/reduce.cpp, plaidml/bridge/openvino/plaidml_util.cpp, plaidml/bridge/openvino/plaidml_util.hpp
The original implementation of `get_axis_set_from_constant_operand` and `get_axis_set_from_constant_operand` use [`op::Constant::get_axis_*_val()`](https://github.com/plaidml/openvino/blob/plaidml/ngraph/core/src/op/constant.cpp#L520) which directly change negative axis value to 0, and fail some tests. 
```cpp
AxisSet op::Constant::get_axis_set_val() const
{
NGRAPH_CHECK(m_element_type.is_integral_number());
std::vector<int64_t> out_axis_set = cast_vector<int64_t>();
AxisSet output_axis_set;
for (auto& axis : out_axis_set)
{
output_axis_set.insert(axis > 0 ? axis : 0);
}
return output_axis_set;
}
```
So, using [`ngraph::normalize_axes`](https://github.com/plaidml/openvino/blob/plaidml/ngraph/core/src/validation_util.cpp#L910) to make all axis to non-negative before casting to `AxisSet` …
=> Fix openvino plaidml util get_axis method

plaidml/bridge/openvino/CMakeLists.txt, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/bucketize.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/scatter_update.cpp
This PR is based on  https://github.com/plaidml/openvino/tree/update-openvino (@tzerrell could you please help push this branch to plaidml branch?), which is rebased onto  https://github.com/openvinotoolkit/openvino/commit/3a86b3a17e3311a69687b8147b6f2317d60b8b82
This update includes upstream fix/update on bucketize, scatter_update, Roi Pooling and Roi Align.
=> Update OpenVINO, including upstream fix on Roi Pooling and Roi Align

plaidml/edsl/tests/edsl_test.cc, pmlc/ast/builder.cc
When layer op has multiple return values, sometimes the order of the values in layer.return is not correct. 
This would cause error in TopK (not submitted yet). 
This patch fixes this issue.
=> Fix layer op

plaidml/bridge/openvino/plugin/plaidml_executable_network.cpp
Add the OpenVINO network-level ConstantFolding pass to the PlaidML OV plugin.
Note that we also considered adding a ConvertReduceToPooling pooling pass. However, this requires us to include ~`transformations/common_optimizations/common_optimizations.hpp`~ [**edit:** actually the file is `transformations/op_conversions/convert_reduce_to_pooling.hpp`], and our build is having trouble finding that file. If we decide we still want this pass, I propose we follow up in another PR that adds the pass and makes the necessary build changes.
=> Add OpenVINO network Constant Folding

plaidml/edsl/tests/edsl_test.cc, plaidml/edsl/tests/edsl_test.py, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
This PR adds stable sort option and let users choose stable/unstable sort while using `edsl::argsort`. Notes are listed below.
1. No new algorithm is added but just modification of the original selection sort. Reference can be found in [wikipedia](https://en.wikipedia.org/wiki/Selection_sort). In short:
> Selection sort can be implemented as a stable sort if, rather than swapping in step 2, the minimum value is inserted into the first position and the intervening values shifted up. However, this modification either requires a data structure that supports efficient insertions or deletions, such as a linked list, or it leads to performing Θ(n2) writes.
Since we don't use linked list in this case, we should be aware that this modification can incur performance impact.
2. Stable sort is …
=> add stable option to argsort op

ci/pipeline.yml, configure, environment.yml, plaidml/bridge/openvino/plaidml_builder.cpp
Turns on Python support when we build OpenVINO. This requires us to include Cython in the .cenv.
Also fixes a warning raised about get_name() being deprecated for ngraph tensor descriptors.
=> Build OpenVINO with Python enabled

plaidml/bridge/openvino/ops/topk.cpp, plaidml/op/lib/ops.cc, plaidml/op/op.h
For those ops that need `TopK` functionality (e.g. `DetectionOutput`) I just re-implement it inside of `detection_output.cpp` in OV bridge. Some other ops that haven't been implemented like `Proposal`, `NonMaxSuppression` in Caffe and MxNet style will need `TopK`, too. Move it into oplib so those ops can call it directly without producing so much redundant code.
=> move topk into oplib

plaidml/bridge/openvino/tests/functional/shared_tests_instances/skip_tests_config.cpp
~The DetectionOutput tests are sporadically failing. We discussed this in the context of #1741 and I had thought this was fixed at the time, but clearly my understanding there was wrong. So, this PR disables those tests for now (to unblock CI), and meanwhile I'm looking into what happened in #1741 and related PRs to see whether we didn't actually land the fix, or if the fix was incomplete, or if there's some additional bug.~
This fixes a bug in DetectionOutput testing by updating the OpenVINO reference to a version that includes the bugfix.
=> Fix DetectionOutput tests

CMakeLists.txt, cmake/pml_cc_test.cmake, cmake/pml_lit_test.cmake, cmake/pml_macros.cmake, cmake/pml_python.cmake, cmake/third_party/llvm-project.cmake, networks/scitile/LAS/CMakeLists.txt, plaidml/bridge/keras/CMakeLists.txt, plaidml/bridge/openvino/tests/functional/CMakeLists.txt, plaidml/edsl/tests/CMakeLists.txt, pmlc/compiler/program.cc, pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc, pmlc/dialect/pxa/analysis/strides.cc, pmlc/dialect/pxa/transforms/fusion.cc, pmlc/dialect/pxa/transforms/layout_utils.cc, pmlc/dialect/pxa/transforms/normalize.cc, pmlc/dialect/pxa/transforms/tile.cc, pmlc/tools/pmlc-jit/pmlc-jit.cc, pmlc/util/CMakeLists.txt, pmlc/util/util.cc, pmlc/util/util.h
Also improves the `check-${CHECK}` targets so that dependencies are properly defined. This ensures that, for instance, `libplaidml.so` is built before running python tests (which depend on `libplaidml.so`).
=> Update to latest MLIR

cmake/pml_cc_test.cmake, cmake/pml_lit_test.cmake, cmake/pml_python.cmake, networks/scitile/LAS/CMakeLists.txt, plaidml/CMakeLists.txt, plaidml/bridge/keras/CMakeLists.txt, plaidml/edsl/tests/CMakeLists.txt
This should resolve issues with fresh builds following this workflow:
```
./configure
cd build-x86_64/Release
ninja check-core
```
=> Fixes for check-XXXX

plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/pooling_smoke.cpp, plaidml/op/lib/ops.cc
Fixing rounding-related error in output size calculation for SAME_UPPER/SAME_LOWER autopad modes.
=> Fixing SAME_UPPER/SAME_LOWER padding

cmake/third_party/llvm-project.cmake, plaidml/edsl/tests/edsl_test.cc, pmlc/compiler/program.cc, pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc, pmlc/dialect/pxa/tests/dataflow_opt.mlir
* Use `CHECK-DAG` for constants checks.
* Remove `EDSC` usage.
Related PR: https://github.com/plaidml/llvm-project/pull/40
=> Update LLVM to latest MLIR

plaidml/bridge/openvino/ops/gather_tree.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/gather_tree.cpp
The inputs shall be integer values even their containers are float type, but the openvino tests will produce illegal inputs when we use CONSTANT type as secondaryInputType, add cast to solve this issue.
=> Do cast to fix illegal inputs of GatherTree.

plaidml/bridge/openvino/ops/detection_output.cpp, plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/detection_output.cpp, plaidml/op/lib/ops.cc, plaidml/op/op.h
Support `share_location` in OpLib `NMS` for `DetectionOutput` and any other ops that will possibly benefit from it.
Note: All the variables in OpLib `NMS` are changed to snake_case in this PR as well.
=> support share_location for DetectionOutput

plaidbench/CMakeLists.txt, plaidbench/plaidbench/__init__.py, plaidml/bridge/keras/__init__.py, plaidml/op/__init__.py, plaidml/op/lib/ops.cc, plaidml/op/op.h, pmlc/conversion/pxa_to_affine/pxa_to_affine.cc, pmlc/conversion/tile_to_pxa/tile_to_pxa.cc, pmlc/dialect/layer/ir/ops.cc, pmlc/dialect/layer/ir/ops.td, pmlc/dialect/pxa/ir/interfaces.td, pmlc/dialect/pxa/ir/ops.td, pmlc/dialect/pxa/transforms/layout_utils.cc, pmlc/dialect/pxa/transforms/simplify_with_constraints.cc, pmlc/dialect/stdx/ir/ops.td, pmlc/dialect/tile/ir/ops.cc, pmlc/dialect/tile/ir/ops.td, pmlc/target/x86/passes.h, pmlc/target/x86/passes.td, pmlc/target/x86/pipeline.cc, pmlc/target/x86/tests/tpp_generic.mlir, pmlc/target/x86/tests/xsmm_lowering.mlir, pmlc/target/x86/xsmm_lowering.cc
* Add special case to oplib relu impl to use new eDSL primitive.
* Add lowering: `tile.relu -> stdx.relu`
* Add `-x86-tpp-patterns` pass to convert `stdx.relu` to `pxa.generic` when possible.
* Add fallback lowering for `stdx.relu -> std.cmpf, std.select` when TPP patterns fail.
=> Lower relu -> TPP

pmlc/dialect/tile/tests/algebraic_opt.mlir, pmlc/dialect/tile/transforms/CMakeLists.txt, pmlc/dialect/tile/transforms/algebraic_opt.cc, pmlc/dialect/tile/transforms/passes.h, pmlc/dialect/tile/transforms/passes.td, pmlc/target/x86/pipeline.cc
First pattern to be implemented does the following.
From:
```
%zero = tile.constant(0.0 : f64)
%0 = tile.contract add, mul, %zero, %I, %K
%1 = tile.add %0, %B
%2 = tile.relu %1
```
Into:
```
%0 = tile.contract add, mul, %B, %I, %K
%2 = tile.relu %0
```
=> Add AlgebraicOpt pass
