plaidml/plaidml

README.md

pip suggests to use -H flag when invoking 'sudo pip'.

added -H flag to sudo

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py
plaidml/op.py

This is a hacky implementation of K.all, basically it does a K.prod and then check if each value of the tensor is equal to 0, if so it stays the same, otherwise it changes to 1. Finally it returns a UINT8 tensor of 1s and 0s as specified in the keras documentation.

Implementation of K.all

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py

Like mentioned on the slack, here the softplus impl.
~It somehow fails the tests on my system, but that might be due to my current setup.~ (Works fine with plaidml 0.6.4rc1)

Added softplus implementation

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py
plaidml/op.py

This is an implementation of K.any, like my previous pull request it's a hacky solution, let me know if anything is wrong or could be better.

Implementation of K.any

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py

This adds the K.logsumexp operation, it's a pretty straightforward implementation and it comes along with unit tests.
Let me know if anything is wrong.

Implementation of K.logsumexp

---

vendor/llvm/llvm.bzl

This is equivalent to https://github.com/plaidml/plaidml/pull/348

Remove histedit dependency

---

plaidml2/bridge/keras/__init__.py
plaidml2/op/__init__.py
plaidml2/op/lib/ops.cc

This adds K.min and K.max functions to the keras backend in plaidml2. 
Let me know if this pull request is okay or if anything is wrong.
Thanks!

Add min and max operations to plaidml2 ops

---

plaidml2/op/lib/ops.cc

Simple fix for a compiler error, just changed a `int64_t` for a `uint64_t`.

Multiple small corrections

---

tile/lang/ast/ast.cc

The `simple_reduce` code in the EDSL gradient was essentially a placeholder / passthrough; this adds the core functionality to complete its implementation.

Add omitted functionality to EDSL simple_reduce

---

.bazelci/presubmit.yml

I'm not convinced that this yml will do the right things for us on the Bazel CI machines. However, as @flaub mentioned, there may be a bit of lead time for the Bazel CI team to respond to our request, so let's merge in what I've got so far and send in the request to their team ASAP.

WIP - Add initial presubmit yml for use with BazelCI

---

demos/TransferLearning/README.md
demos/TransferLearning/TransferLearningDemo.ipynb
demos/TransferLearning/TransferLearningDemo.py
demos/TransferLearning/requirements.txt

Uploading the cats dogs demo for easy access

Transfer Learning (dogs and cats) demo

---

plaidml/keras/backend.py

The bug occurs when minval equals maxval.

fix random uniform problem

---

README.md
docs/building.md
docs/troubleshooting.md

Updating documentation to address the following:
* Command line options in `configure` script
* Updated troubleshooting docs and made them more accessible from the `README`

WIP - Documentation Updates

---

plaidml/keras/backend_test.py
tile/codegen/pad.cc
tile/codegen/thread_inner.cc
tile/lang/gen_stripe.cc

- Relax the assertion in thread inner pass
- Fix padding output refinement
- Fix duplicated stores in eltwise op

Fix some bugs for running nGraph training

---

plaidbench/plaidbench/core.py
plaidbench/plaidbench/frontend_keras.py
plaidml2/bridge/keras/__init__.py

Expand the plaidbench network-level batchnorm folding so as to produce relevant perf metrics for EDSL-based PlaidML while waiting for the relevant constant folding to be fully implemented.

Extend plaidbench batchnorm folding

---

tile/lang/gen_stripe.cc

The type of the EQ statement should not be boolean, but the supertype of all it's parameters. This way the right casting operations will be done in the backend jit.

Set proper type to the EQ statement.

---

tile/codegen/aggrinit.cc
tile/codegen/aggrinit.h
tile/codegen/codegen.proto
tile/targets/cpu/llvm_cpu.jsonnet

This takes care of proper initialization of the agg_op outputs and new locals.

Add initial implementation of AggregationBlockOutputInitializationPass

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py

Title is self-explanatory.
Let me know if anything is wrong.

Implement K.softsign() in plaidml keras backend

---

plaidml2/bridge/keras/backend_test.py

Remove spurious plaidml2 tf session close

---

tile/codegen/aggrinit.cc

A block can have multiple outputs and a assign/aggregation contraction transition could happen on any of these outputs. Make sure all the output aggregations are properly initialized.

Initialize all the aggregation outputs

---

pmlc/conversion/stripe_to_affine/convert_stripe_to_affine.cc

Debug build was broken in convert_stripe_to_affine.cc

[MLIR] Fix debug build

---

plaidml2/bridge/keras/backend_test.py
plaidml2/edsl/edsl.h
plaidml2/edsl/ffi.cc
plaidml2/edsl/ffi.h
plaidml2/op/lib/ops.cc
pmlc/dialect/tile/builder.cc
pmlc/dialect/tile/builder.h
pmlc/dialect/tile/ops.cc
pmlc/dialect/tile/ops.td
tile/lang/ast/ast.cc
tile/lang/ast/ast.h
tile/lang/ast/fold.cc

Support taking the `max` or `min` of two `TensorDim`s

Add max & min for TensorDim

---

pmlc/dialect/stripe/stripe_test.cc
tile/lib/lib.cc
tile/lib/lib.h

Thanks to the new modular stripe_test.cc design, I'm adding the MaxPool2d test I've been experimenting with as one of the standard tests.

Add MaxPool stripe_test

---

plaidml2/edsl/edsl_test.cc
pmlc/dialect/stripe/from_mlir.cc
pmlc/dialect/stripe/tests/translate/double_dot.pbtxt
pmlc/dialect/tile/tests/legalize-to-stripe.mlir
pmlc/dialect/tile/tests/translate-to-stripe.mlir

Try to make tests less fragile

Improve tests & fix bugs

---

plaidml2/op/op.h
plaidml2/op/op_test.cc

I added wrappers for the following operations:
- Prod
- ~Relu~ (to be included in a different PR)
- Repeat
- Slice
- Softmax
- SpatialPadding

some more op lib wrappers

---

plaidml2/op/op.h
plaidml2/op/op_test.cc

binary_crossentropy
clip
cumprod
cumsum
dot

oplib wrappers

---

plaidml2/op/op.h
plaidml2/op/op_test.cc

oplib wrapper concatenate

---

plaidml2/op/lib/ops.cc
plaidml2/op/op_test.cc

@flaub I'm not exactly sure what you meant when you asked us to provide context to support event logging -- does this just mean add a bunch of `IVLOG` statements or should I actually be doing something with the `ctx` object?

add tests and event logging for variance

---

plaidml/BUILD
plaidml/not_setup.cfg
tile/pmlc/BUILD

The upcoming MLIR path will render this obsolete

Drop pmlc binary

---

bzl/bazel.rc
plaidml/keras/BUILD
pmlc/dialect/eltwise/dialect.cc
pmlc/dialect/eltwise/ops.cc
pmlc/dialect/eltwise/ops.td
pmlc/dialect/eltwise/predicates.td
pmlc/dialect/eltwise/tests/constant-fold.mlir
pmlc/dialect/eltwise/util.cc
pmlc/dialect/stripe/dialect.cc
pmlc/dialect/stripe/into_mlir.cc
pmlc/dialect/stripe/ops.cc
pmlc/dialect/stripe/ops.td
pmlc/dialect/stripe/rewrites.cc
pmlc/dialect/stripe/rewrites.h
pmlc/dialect/stripe/tests/canonicalize.mlir
pmlc/dialect/stripe/tests/jigsaw.mlir
pmlc/dialect/tile/builder.cc
pmlc/dialect/tile/lowering.cc
pmlc/dialect/tile/ops.h
pmlc/dialect/tile/ops.td
pmlc/dialect/tile/tests/legalize-to-stripe.mlir
pmlc/dialect/tile/tests/translate-to-stripe.mlir

This reverts commit e9b42d9b66f582ddaf49e74e67b19000d46e67df.

Revert " Allow immediate scalar types for eltwise dialect (#700)"

---

pmlc/conversion/stripe_to_affine/convert_stripe_to_affine.cc
pmlc/conversion/tests/stripe_affine_roundtrip/parallel_for.mlir

Initial support for multi-dimentional ParallelForOp.

[MLIR] Add support for ParallelForOp to Stripe->Affine

---

bzl/workspace.bzl
networks/oplib/BUILD
networks/oplib/resnet50.cc
plaidml2/bridge/keras/__init__.py
plaidml2/bridge/keras/backend_test.py
plaidml2/core/core.h
plaidml2/edsl/__init__.py
plaidml2/edsl/edsl_test.cc
plaidml2/edsl/ffi.cc
plaidml2/exec/exec.h
plaidml2/exec/ffi.cc
plaidml2/op/op_test.cc
pmlc/dialect/tile/builder.cc
pmlc/dialect/tile/builder.h

Add benchmarking of resnet50

---

tile/codegen/alias.cc
tile/codegen/alias.h
tile/codegen/autotile.cc
tile/codegen/cache.cc
tile/codegen/codegen.proto
tile/codegen/idx_order.cc
tile/codegen/idx_order.h
tile/codegen/reg_cache.cc
tile/ocl_exec/emitsem.cc
tile/stripe/stripe.cc
tile/stripe/stripe.h
tile/targets/gpu/amd.jsonnet
tile/targets/gpu/nvidia.jsonnet

* New register cache pass
* New index order pass
* Autotile considers small prime factors in inner block
* Fix OpenCL/Metal emitter bug
* Fix bug in cache pass

Improve GPU performance and fix bugs

---

docs/docs/edsl.md

as discussed changing the incorrect index in edsl doc

minor doc fix

---

plaidml/keras/backend.py
plaidml/keras/backend_test.py

Title is self-explanatory, let me know if anything can be improved.
Fixes #841

Add separable_conv1d to keras backend

---

pmlc/conversion/pxa_to_affine/pxa_to_affine.cc
pmlc/conversion/tile_to_pxa/tests/compare.mlir
pmlc/conversion/tile_to_pxa/tests/dot.mlir
pmlc/conversion/tile_to_pxa/tests/double_dot.mlir
pmlc/conversion/tile_to_pxa/tests/eltwise_add.mlir
pmlc/conversion/tile_to_pxa/tests/relu.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/dialect/pxa/ir/ops.cc
pmlc/dialect/pxa/ir/ops.td

Using upper/lower bounds did make interop easier.

Adjust parallel for to match curent RFC

---

ci/conda/keras_backend_test.yml
ci/conda/ml_gpu.yml
ci/conda/tensorflow-dnnl.yml
ci/conda/tensorflow.yml
conda/unix.yml
conda/windows.yml
environment-windows.yml
environment.yml

Related bugs:
https://github.com/pypa/pip/issues/7626
https://github.com/pypa/pip/issues/7629

Avoid broken pip 20

---

plaidbench/plaidbench.py
plaidbench/plaidbench/frontend_keras.py
plaidbench/plaidbench/networks/keras/resnet50_v2.py
plaidbench/plaidbench/networks/keras/resnext50.py

imported networks in keras_applications instead of keras itself.

Adding resnet50_v2 and resnext50 to plaidbench

---

tools/heatmap/build_defs.bzl

correctly inherit environment variables

---

plaidml/edsl/edsl_test.cc
pmlc/conversion/tile_to_pxa/tests/bit_right_scalar.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc

Minimal change of https://github.com/plaidml/plaidml/pull/859/

Added bit-right for unsigned dtype

---

plaidml/edsl/edsl_test.cc
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc

Add tile to pxa conversion for the sqrt operation.

---

plaidml/bridge/keras/__init__.py

The Tensor class used to have a shape attribute; this updates the keras backend to use the rank or dtype properties instead, or the compute_shape() method.

update keras backend to accommodate Tensor API changes (shape/rank)

---

pmlc/conversion/tile_to_pxa/tests/padding.mlir
pmlc/dialect/tile/tests/padding.mlir
pmlc/dialect/tile/transforms/padding.cc

Remove constraints after padding.

Remove constraints on padding

---

demos/mlsys_2020/app.py
demos/mlsys_2020/core.py
demos/mlsys_2020/edsl_demo.ipynb
demos/mlsys_2020/lowering_demo.ipynb

Its in between modifications for Denise to look at.

Lowering Demo Functionality

---

environment-windows.yml
pmlc/dialect/pxa/tests/stencil.mlir
pmlc/dialect/pxa/transforms/passes.h
pmlc/dialect/pxa/transforms/registration.cc
pmlc/dialect/pxa/transforms/stencil.cc
pmlc/target/x86/BUILD
pmlc/target/x86/heatmap.h
pmlc/target/x86/heatmap.tpl.cc
pmlc/target/x86/heatmap_impl.cc
pmlc/target/x86/pipeline.cc

Added a costing function in the heatmap itself and passing it to the stencil pass.

Integrated the heat map into the stencil pass

---

plaidml/edsl/autodiff.h
plaidml/edsl/edsl.h

Compatibilty with older C++ compilers

---

ci/plan.yml
plaidml/bridge/keras/backend_test.py
plaidml/core/ffi.cc

Fix for calculating buffer sizes when calling from Python to plaidml

---

plaidml/edsl/tests/edsl_test.cc
pmlc/conversion/tile_to_pxa/tests/prng.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/rt/BUILD
pmlc/rt/prng.cc

This PR implements Prng function implementation using the MLIR.

Initial implementation of PRNG function using MLIR

---

pmlc/rt/prng.cc

Keras expects only positove random numbers.

Use unsigned ints instead of ints

---

plaidml/bridge/keras/__init__.py

Fix resize_vols by checking the data_format in normalized form.

Fix resize_vols data_format

---

pmlc/conversion/gpu/gpu_to_vulkan.cc
pmlc/conversion/gpu/kernel_outlining.cc
pmlc/rt/vulkan/tests/addf.mlir
pmlc/rt/vulkan/wrappers.cc
vendor/openvino/repo.bzl

Add vulkan rt support to integer and float types.
Refactored buffer binding functions.

Add vulkan integer and float datatype support

---

pmlc/conversion/pxa_to_affine/pxa_to_affine.cc

Cleanup based on comments I saw post-merge on #1054

Clean AffineParallelOpConversion

---

pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc
pmlc/conversion/stdx_to_llvm/tests/reshape.mlir
pmlc/conversion/tile_to_pxa/tests/reshape.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/dialect/stdx/ir/ops.cc
pmlc/dialect/stdx/ir/ops.td

tile.reshape -> stdx.reshape -> view rewrite

---

plaidml/op/op.h

Issue with initialization was observed while working on onnxRT

EDSL Fluent API: convolution default parameters fix

---

bzl/workspace.bzl

we had a couple of changes to internal memory manager over the last month

Updating to latest LIBXSMM

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/multiply.cpp
plaidml/bridge/openvino/src/plaidml_plugin/plaidml_executable_network.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/multiply.cpp
vendor/openvino/workspace.bzl

(Ready for review, ~but depends on https://github.com/plaidml/openvino/pull/3 and needs to land after it; it may require a commit hash update.~)
Adds support for the OpenVINO ops Constant and Multiply.

Add OpenVINO Constant & Multiply

---

plaidml/op/lib/ops.cc
plaidml/op/op.h
plaidml/op/op_test.cc
plaidml/testenv.h

Revert "Add broadcast to op lib"

---

plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/transpose.cpp

(I plan to bundle multiple ops into one PR for future tests, but I wanted to get one out there for now.)
Note that this depends on https://github.com/plaidml/openvino/pull/6 (and so is a draft until that lands)

Add OpenVINO plugin transpose test cases

---

plaidml/op/lib/ops.cc
plaidml/op/op.h
plaidml/op/op_test.cc
plaidml/testenv.h

Broadcast op

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/squared_difference.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/squared_difference.cpp
vendor/openvino/workspace.bzl

Implemented squared difference op + test

squared difference op

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/group_convolution.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/group_convolution_backprop_data.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD

This needs #1149 to land first

Add OpenVINO plugin grouped convolution

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/depth_to_space.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/space_to_depth.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/depth_to_space.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/space_to_depth.cpp
vendor/openvino/workspace.bzl

Note that these have somewhat different implementations, one using a more complex contraction, one using a simpler contraction followed by a reshape; this works around a bug that was showing up in defractionalization.
~Can't land until https://github.com/plaidml/openvino/pull/14 is in.~

Add OpenVINO ops DepthToSpace & SpaceToDepth

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/mat_mul.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/mat_mul.cpp
vendor/openvino/workspace.bzl

Issues on OV side preventing testing from running (receiving `"Unsupported operation: MatMul"` error)

Adding matmul op (untested)

---

vendor/openvino/workspace.bzl

(Forgot to add in new hash with last update to OV reference)

Added openvino sha256 hash

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/cosh.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/sinh.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/cosh.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/sinh.cpp

Explicit formulas for sinh and cosh used since elementwise sinh and cosh operations are not yet implemented.

Added openvino sinh and cosh ops

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/hard_sigmoid.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/hard_sigmoid.cpp
vendor/openvino/workspace.bzl

Added hardsigmoid op and updated OV reference to version that allows test arguments with decimals

Added openvino hardsigmoid op

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/cos.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/divide.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/sin.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/subtract.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/cos.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/divide.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/sin.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/subtract.cpp

Openvino ops Div, Subtract, Sin, Cos

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/reduce_logical_or.cpp

Fixed layer attribute reference in ReduceLogicalOr

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/strided_slice.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/strided_slice.cpp
plaidml/op/op.h
vendor/openvino/openvino.BUILD
vendor/openvino/workspace.bzl

@dgkutnic and @flaub I've included you as reviewers just so you can see the small extension to the oplib Slice API that's in this PR (there are unique semantics from passing `None`s to Slice which I needed, so this PR adds a way to do so).

Add OpenVINO op StridedSlice

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/select.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD
vendor/openvino/workspace.bzl

This is @cnamrata15's code for select from #1141 plus an OV pointer bump; I'm probably more accurately an approving reviewer of this PR rather than the author.

Add OpenVINO op Select

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/logical_and.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/logical_or.cpp
plaidml/bridge/openvino/src/plaidml_plugin/ops/logical_xor.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/logical_and.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/logical_or.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/logical_xor.cpp

Tests fail as inputs need to be boolean.

Openvino : Logical Ops

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/pad.cpp
plaidml/op/lib/ops.cc
plaidml/op/op.h
plaidml/op/op_test.cc

- Changed treatment of padval argument from double to Value for easier passing from TF & better handling of data type
- Implemented fluent API

Modify explicit_padding op

---

plaidml/bridge/keras/__init__.py
plaidml/bridge/keras/backend_test.py

implicit bool cast on keras switch op resolves eltwise.select issue

---

plaidml/bridge/keras/backend_test.py
pmlc/conversion/tile_to_pxa/tests/eltwise.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc

enable eltwise.pow when one or more args are int

---

plaidml/bridge/openvino/src/plaidml_plugin/ops/mvn.cpp
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/BUILD
plaidml/bridge/openvino/tests/functional/plugin/plaidml/shared_tests_instances/single_layer_tests/mvn.cpp
plaidml/op/lib/ops.cc
plaidml/op/op.h

Depends on https://github.com/plaidml/openvino/pull/5, will be a draft until that lands.

Add MVN to OpenVINO plugin

---

pmlc/dialect/pxa/tests/vectorize.mlir
pmlc/dialect/pxa/transforms/vectorize.cc

Vectorization for reduces forgot to do a broadcast.

Fixed a small vectorization bug and added a test.

---

pmlc/dialect/stdx/ir/ops.cc
pmlc/dialect/stdx/ir/ops.h
pmlc/dialect/stdx/ir/ops.td
pmlc/target/x86/pipeline.cc

This will insert dellocs where appropriate to prevent getting OOMs.

Add BufferPlacementPass to x86 target pipeline

---

pmlc/dialect/pxa/analysis/strides.cc
pmlc/dialect/pxa/analysis/uses.cc
pmlc/dialect/pxa/analysis/uses.h
pmlc/dialect/pxa/ir/ops.cc
pmlc/dialect/pxa/ir/ops.td
pmlc/dialect/pxa/transforms/cache.cc
pmlc/dialect/pxa/transforms/tile.cc
pmlc/dialect/pxa/transforms/tile.h
pmlc/dialect/pxa/transforms/vectorize.cc
pmlc/dialect/pxa/transforms/vectorize.h

Add proper canonicalizer.
Add builder.
Fix minor bugs from earlier refactoring.
Slightly improved vectorization support that accidentally made it in this commit.

Bring pxa.vector_load into conformance with other load/stores

---

pmlc/conversion/gpu/gpu_to_vulkan.cc

This is a follow-up to the work and discussion with Adam.
After this patch, the compilation time of resnet50 on vulkan is reduced from a few minutes to about 17 seconds.
The command to test resnet50 on vulkan is,
PLAIDML_TARGET="intel_gen" bazelisk run --//plaidml:target=intel_gen //plaidbench:bin -- -n 1 keras resnet50
Note that in order to run the above command, Prng lowering pattern needs to be added to gpu pipeline and libplaidml.so needs to be linked to vulkan runtime.

Improve gpu to vulkan compilation time

---

plaidml/edsl/tests/edsl_test.cc
pmlc/conversion/tile_to_pxa/tests/scatter.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/dialect/tile/ir/ops.td

implement tile.scatter

---

bzl/workspace.bzl
pmlc/rt/executable.cc
pmlc/rt/symbol_registry.cc
pmlc/rt/symbol_registry.h
vendor/tensorflow/kinetics-i3d.BUILD

Fix symbol resolution under MacOS

---

pmlc/conversion/gpu/gpu_to_vulkan.cc
pmlc/rt/vulkan/vulkan_device.cc
pmlc/rt/vulkan/vulkan_invocation.cc
pmlc/rt/vulkan/vulkan_invocation.h
pmlc/rt/vulkan/wrappers.cc
pmlc/target/intel_gen/tests/dotf.mlir
pmlc/target/intel_gen/tests/e2e.mlir
pmlc/target/intel_gen/tests/intermediate.mlir

Select compute queue family based on priority to support timestamps better.
Code clean up.

Fix select compute queue

---

pmlc/all_passes.h
pmlc/dialect/comp/BUILD
pmlc/dialect/comp/tests/execenv_coalescing.mlir
pmlc/dialect/comp/transforms/BUILD
pmlc/dialect/comp/transforms/execenv_coalescing.cc
pmlc/dialect/comp/transforms/pass_detail.h
pmlc/dialect/comp/transforms/passes.h
pmlc/dialect/comp/transforms/passes.td
pmlc/target/intel_gen_ocl_spirv/BUILD
pmlc/target/intel_gen_ocl_spirv/pipeline.cc

Closes #1409 - it's enough to reduce ResNet to single execution environment.

[comp] Add basic execenv coalescing pass

---

pmlc/conversion/gpu/kernel_outlining.cc
pmlc/conversion/gpu_to_spirv/gpu_to_spirv.cc
pmlc/conversion/gpu_to_spirv/tests/subgroups_broadcast.mlir
pmlc/dialect/pxa/transforms/fusion.cc
pmlc/target/intel_gen/subgroup_broadcast.cc
pmlc/target/intel_gen_ocl_spirv/pipeline.cc
pmlc/target/intel_gen_ocl_spirv/spirv_target.cc

Also added spirv lowerings after llvm upstream update

Block ops enabled for OpenCL

---

pmlc/conversion/gpu/gpu_to_vulkan.cc

Waiting for llvm upstream update to push this in

subgroup size control use subgroupSize attribute

---

pmlc/target/intel_gen/subgroup_broadcast.cc
pmlc/target/intel_gen/tests/subgroup_block_ops.mlir
pmlc/target/intel_gen/tests/subgroup_broadcast.mlir
pmlc/target/intel_gen_ocl_spirv/pipeline.cc

- LoopInvariantCodeMotionPass to reduce redundant mem reads in the generated code
- llvm's data flow opt to remove redundant buffers after loop unrolling
- changed condition to enable block ops for more buffers
These changes give few % boost on my machine.

Some lowering code improvements

---

pmlc/compiler/program.cc
pmlc/compiler/program.h
pmlc/conversion/gpu_to_spirv/gpu_to_spirv.cc
pmlc/conversion/gpu_to_spirv/passes.h
pmlc/conversion/gpu_to_spirv/passes.td
pmlc/target/intel_gen/pipeline.cc
pmlc/target/intel_gen/subgroup_broadcast.cc
pmlc/target/intel_gen_ocl_spirv/passes.h
pmlc/target/intel_gen_ocl_spirv/passes.td
pmlc/target/intel_gen_ocl_spirv/pipeline.cc
pmlc/target/intel_gen_ocl_spirv/spirv_target.cc
pmlc/target/x86/register.cc

Usage e.g.  PLAIDML_TARGET="intel_gen_ocl_spirv{use-block-ops=false spirv-version=120}"

Adding Gen pipeline options

---

plaidml/edsl/tests/edsl_test.cc
pmlc/conversion/pxa_to_affine/BUILD
pmlc/conversion/pxa_to_affine/CMakeLists.txt
pmlc/conversion/pxa_to_affine/pxa_to_affine.cc
pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc
pmlc/conversion/stdx_to_llvm/tests/pack.mlir
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/dialect/stdx/ir/ops.cc
pmlc/dialect/stdx/ir/ops.h
pmlc/dialect/stdx/ir/ops.td
pmlc/dialect/tile/transforms/BUILD
pmlc/dialect/tile/transforms/CMakeLists.txt
pmlc/dialect/tile/transforms/passes.h
pmlc/dialect/tile/transforms/passes.td
pmlc/dialect/tile/transforms/split_main.cc
pmlc/rt/jit_executable.cc
pmlc/target/x86/pipeline.cc
pmlc/util/util.cc

Initial 'it does something' version of init-fini code.

Enable init/fini on CPU path

---

plaidml/bridge/openvino/ops/one_hot.cpp

Clean up comments remained in PR plaidml#1640.

Onehot implementation code cleanup

---

plaidml/bridge/openvino/ops/roi_pooling.cpp
plaidml/bridge/openvino/ops/shuffle_channels.cpp

Fix ROIPooling op code(from https://github.com/plaidml/plaidml/pull/1638), and fix ShuffleChannel code(from https://github.com/plaidml/plaidml/pull/1577)

Fix ROIPooling and ShuffleChannel code

---

bzl/workspace.bzl
cmake/pml_tblgen_library.cmake
cmake/third_party/llvm-project.cmake
plaidml/bridge/openvino/ops/embedding_segments_sum.cpp
plaidml/bridge/openvino/ops/roi_align.cpp

This depends on https://github.com/plaidml/llvm-project/pull/32

Add support for cross compilation

---

pmlc/BUILD
pmlc/CMakeLists.txt
pmlc/all_passes.h
pmlc/conversion/comp_to_llvm/comp_to_llvm.cc
pmlc/conversion/gpu/BUILD
pmlc/conversion/gpu/kernel_outlining.cc
pmlc/dialect/comp/ir/ops.td
pmlc/dialect/stdx/tests/i1_to_i32.mlir
pmlc/dialect/stdx/transforms/i1_to_i32.cc
pmlc/dialect/stdx/transforms/pass_detail.h
pmlc/dialect/stdx/transforms/passes.td
pmlc/rt/jit_executable.cc
pmlc/rt/opencl/opencl_invocation.cc
pmlc/rt/opencl/opencl_wrappers.cc
pmlc/target/intel_gen_ocl_spirv/pipeline.cc
pmlc/transforms/hoisting.cc
pmlc/util/memuse.cc
pmlc/util/memuse.h

Add support for hoisting kernel creation into init.

---

pmlc/target/intel_gen_ocl_spirv/pipeline.cc

https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/INTEL/SPV_INTEL_subgroups.asciidoc

enable block ops for OCL pipeline

---

conda/unix.yml
environment-windows.yml

Typo in environment-windows.yml

Pin pyyaml

---

plaidml/bridge/openvino/ops/batch_norm_inference.cpp

Signed-off-by: xin1.wang <xin1.wang@intel.com>

Remove some comments of BatchNormInference.

---

plaidml/bridge/openvino/ops/reduce.cpp

Do fixup and make output tensor datatype following input datatype.

Fixup openvino reduce logical ops

---

plaidml/bridge/openvino/ops/gather_nd.cpp
pmlc/ast/ast_ops.cc
pmlc/ast/builder.cc
pmlc/conversion/tile_to_pxa/tile_to_pxa.cc
pmlc/dialect/tile/ir/ops.cc
pmlc/dialect/tile/ir/ops.td

Addressed per Tim and Frank's comments in #1695 and fixed some other naming issues.

Fix GatherND typos

---

plaidml/bridge/openvino/CMakeLists.txt
plaidml/bridge/openvino/ops/roi_align.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/roi_align.cpp

This PR works with somes fix on OV reference implementation in https://github.com/plaidml/openvino/pull/136.

Fix ROI Align

---

plaidml/edsl/edsl.h
plaidml/op/__init__.py
plaidml/op/lib/ops.cc
plaidml/op/op.h
plaidml/op/op_test.cc

Add multi-D sort in oplib using edsl::gather ND mode and edsl::argsort

Add multi-D sort

---

configure
plaidml/bridge/openvino/ops/unsqueeze.cpp

- Fixes issue with unsqueeze bridge
- Also fixes minor typo in configure preventing conda env from being created

Add coverage for STN network

---

plaidml/bridge/openvino/plaidml_builder.cpp
plaidml/bridge/openvino/plaidml_builder.hpp

buildNodeProgram : Creates EDSL program from a single ngraph Node

buildNodeProgram : API to build edsl program fron ngraph Node

---

plaidml/bridge/openvino/ops/detection_output.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/detection_output.cpp
plaidml/op/lib/ops.cc
plaidml/op/op.h

This PR does not change much of the original NMS code. It basically adds pre-process for different styles of NMS.

support decrease_label_id for DetectionOutput

---

pmlc/dialect/pxa/tests/fusion-tiled.mlir
pmlc/dialect/pxa/transforms/fusion.cc
pmlc/dialect/pxa/transforms/passes.td

Fix bugs and design issues with tiled fusion, remove support for subgroup handling + GPU specific refactoring.

Fix tiled fusion

---

cmake/third_party/llvm-project.cmake
pmlc/conversion/stdx_to_llvm/tests/reshape.mlir
pmlc/target/x86/tests/xsmm_call.mlir

Related PR: https://github.com/plaidml/llvm-project/pull/42

Update LLVM to latest upstream

---

plaidml/bridge/openvino/ops/broadcast.cpp
plaidml/bridge/openvino/ops/normalize_l2.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/broadcast.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/fake_quantize.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/normalize_l2.cpp
plaidml/bridge/openvino/tests/functional/shared_tests_instances/single_layer_tests/pad.cpp
plaidml/op/lib/ops.cc

Add openvino missing tests for `broadcast`, `fake_quantize`, `normalized_l2`, `pad`.
Fix which fails test.

Add openvino missing tests 

---

pmlc/all_dialects.cc
pmlc/ast/builder.cc
pmlc/dialect/pxa/transforms/CMakeLists.txt
pmlc/dialect/pxa/transforms/stencil.cc
pmlc/dialect/pxa/transforms/stencil.h
pmlc/dialect/pxa/transforms/stencil_gemm.cc
pmlc/target/x86/stencil_tpp_unary.cc
pmlc/target/x86/tests/stencil_tpp_gemm.mlir
pmlc/util/CMakeLists.txt
pmlc/util/schedule.cc
pmlc/util/schedule.h
pmlc/util/schedule.td

* Resolves #1828 
* Resolves #1829

Add ScheduleAttr and apply it to StencilPass

---

cmake/third_party/llvm-project.cmake
pmlc/conversion/stdx_to_llvm/CMakeLists.txt
pmlc/conversion/stdx_to_llvm/stdx_to_llvm.cc
pmlc/dialect/layer/ir/CMakeLists.txt
pmlc/dialect/layer/ir/ops.cc
pmlc/dialect/pml/ir/CMakeLists.txt
pmlc/dialect/pml/ir/dialect.cc
pmlc/dialect/pxa/ir/CMakeLists.txt
pmlc/dialect/pxa/ir/ops.cc
pmlc/dialect/stdx/ir/CMakeLists.txt
pmlc/dialect/stdx/ir/ops.cc
pmlc/dialect/tile/ir/CMakeLists.txt
pmlc/dialect/tile/ir/dialect.cc
pmlc/dialect/xsmm/ir/CMakeLists.txt
pmlc/dialect/xsmm/ir/ops.cc
pmlc/rt/tests/boundscheck-rt.mlir
pmlc/target/x86/CMakeLists.txt
pmlc/target/x86/pipeline.cc
pmlc/target/x86/xsmm_lowering.cc

Corresponding PR: https://github.com/plaidml/llvm-project/pull/43

Update LLVM/MLIR to latest upstream

---

ci/conda/keras_backend_test.yml
ci/conda/ml_gpu.yml
ci/conda/tensorflow-dnnl.yml
ci/conda/tensorflow.yml
conda/unix.yml
conda/windows.yml

Hopes to resolve issue #1705 
Please squash my dumb commits it should be one

Lock h5py version at 2.10.0

---

demos/TransferLearning/TransferLearningDemo.py

Fix to get correct directories in demos/TransferLearning
